### ISSUE TITLE
Nullable field causing type assignment error

### ISSUE THREAD

**Issue by jas99** [prisma/graphqlgen#50] opened 2018-09-28 11:30 UTC
Hey @divyenduz @timsuchanek 
Steps to reproduce

Use below schema.graphql and yield fresh interfaces and scaffold.
```
type Query {
  me: User
}

type Mutation {
  signup(name: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
}

type AuthPayload {
  token: String!
  user: User!
}

# The `User` type is a reduced version ("mask") of the `User` type from the data model (and database schema).
# It does not expose the `createdAt`, `updatedAt` and `password` fields.
type User {
  id: ID!
  email: String!
  name: String
}

```

Following type error is produced 
![screenshot 9](https://user-images.githubusercontent.com/1231593/46205870-e3fa7c80-c33f-11e8-8585-1a901331b121.png)

```
{
	"resource": "/c:/Users/jas/play/prt2/src/resolvers/User.ts",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '(parent: UserParent) => string | undefined' is not assignable to type '(parent: UserParent, args: {}, ctx: Context, info: GraphQLResolveInfo) => string | Promise<string | null> | null'.\n  Type 'string | undefined' is not assignable to type 'string | Promise<string | null> | null'.\n    Type 'undefined' is not assignable to type 'string | Promise<string | null> | null'.",
	"source": "ts",
	"startLineNumber": 13,
	"startColumn": 3,
	"endLineNumber": 13,
	"endColumn": 7,
	"relatedInformation": [
		{
			"startLineNumber": 138,
			"startColumn": 5,
			"endLineNumber": 138,
			"endColumn": 9,
			"message": "The expected type comes from property 'name' which is declared here on type 'Type<TypeMap>'",
			"resource": "/c:/Users/jas/play/prt2/src/generated/resolvers.ts"
		}
	]
}
```

**Comment by jas99** [comment] 2018-09-28 11:34
**Cause of error:**
Interfaces use null but resolver using undefined; for making property nullable.

I will be adding PR to this thread that will change interface to use undefined instead of null.
Although you the choose reverse if you want to.

Thx

**Comment by jas99** [comment] 2018-09-29 05:15
@divyenduz I think you should research code from https://github.com/dotansimha/graphql-code-generator

**Comment by divyenduz** [comment] 2018-09-29 09:59
@jas99 : Can you please share the version of your `graphql-resolver-codegen` by using `graphql-resolver-codegen --version`

**Comment by jas99** [comment] 2018-09-29 16:09
Hey @divyenduz 
I was testing against the basic schema from fixtures in this repo.
The resolver generation issue might be related to error in schema itself.
```
custom_with_custom_arg(id: Number!): Number!
scalar_with_custom_arg(id: Number!): Boolean!
```
I don't think one can use types as arguments, doesn't it has to be input type?

**Comment by divyenduz** [comment] 2018-09-29 17:52
Yes, it has to be an input type. This looks like a bug.

**Comment by kevinmarrec** [comment] 2018-10-09 09:51
@divyenduz Any Update on this issue ?
@jas99 proposed https://github.com/prisma/graphql-resolver-codegen/pull/52

**Comment by kevinmarrec** [comment] 2018-10-09 13:09
And this issue only happens when having `strictNullChecks: true` in `tsconfig.json`, if I'm right.

**Comment by jas99** [comment] 2018-10-09 13:45
@kevinmarrec No that was not the issue. Generated interfaces returns Null but the scaffold is generating undefined type instead of null; which causes type mismatch.

**Comment by kevinmarrec** [comment] 2018-10-09 14:06
Oh yeah I got confused ^^, but anyway the error which allowed you to see the issue could only happen with the `strictNullChecks: true` option (or `strict: true`). Cause without it TypeScript doesn't seem to care if your resolver return `null` instead of `undefined` ^^.

So the PR is fixing the scaffolding and when we want to do things by ourselves it's about replacing `variable?: Type` by `variable: Type | null` right ? If I correctly understood what you did.

**Comment by jas99** [comment] 2018-10-09 14:09
@kevinmarrec Right on.. actually for some weird reason @divyenduz intentionally introduced undefined which might not be inline with graphqljs implementation.

**Comment by divyenduz** [comment] 2018-10-09 14:14
@jas99 : Thanks! that makes sense, can you please create a minimal reproduction project with `strictNullChecks: true`

In the mean time, can you also please create an issue for the input issue, hopefully with a reproduction 🙏 

I will try to get both these resolved ASAP. Thanks!

**Comment by jas99** [comment] 2018-10-09 14:37
@divyenduz Buddy is true by default "strict": true" which means strickNullCheckts is also true and the issue with type-mismatch was not edge case.

typescript-graphql-auth in example has user with nullable property.
https://github.com/prisma/prisma-examples/blob/master/typescript-graphql-auth/src/resolvers/User.ts

If you lint it you will see the issue.

![screenshot 10](https://user-images.githubusercontent.com/1231593/46220808-ed4c0f00-c368-11e8-80b7-b7b937dad1d2.png)

Please re-read the very first comment. I have reattached the pic.

PS: My pr #52 fixes this. I will merge PR with recent update from master.

Thx

**Comment by kevinmarrec** [comment] 2018-10-10 12:37
@jas99 Removing the `?` and replacing by `| null` in [Model]Parent interfaces seems to break Types for Mutations and Queries :/

![screenshot_2](https://user-images.githubusercontent.com/25272043/46736737-0ffbf300-cc9a-11e8-8026-96ead5293363.png)
![screenshot_1](https://user-images.githubusercontent.com/25272043/46736698-f3f85180-cc99-11e8-8140-db388cc40fde.png)

**Comment by kevinmarrec** [comment] 2018-10-10 12:43
I think the solution is on resolver generation, when a field is not required it should be (for a string) :

`string | undefined`
or maybe
`string | undefined | null`

But not
`string | null`

**Comment by kevinmarrec** [comment] 2018-10-10 12:46
@jas99 As far as I know, the problem is :

Typescript `?` means `| undefined`

But in GraphQL Language it means `| null`

**Comment by divyenduz** [comment] 2018-10-10 12:50
@jas99 @kevinmarrec : Can anyone of you prepare a minimal reproduction repository? Currently, I just have some code + an image. Real code would help 🙏

**Comment by jas99** [comment] 2018-10-10 13:30
@kevinmarrec I personally use https://www.npmjs.com/package/@jas99/graphql-resolver-codegen
Generate both interfaces and scaffold with this variant; its tested by me.

**Comment by kevinmarrec** [comment] 2018-10-10 13:32
@divyenduz  https://github.com/kevinmarrec/typescript-prisma-minimal
1) You should have a TS lint error in resolvers/User.ts
2) Replace `notRequiredField?: string` by `notRequiredField: string | null`
3) Problem in 1) solved BUT new error in Query.ts

**Comment by jas99** [comment] 2018-10-10 13:33
@divyenduz https://github.com/prisma/prisma-examples/tree/master/typescript-graphql-auth

**Comment by kevinmarrec** [comment] 2018-10-10 13:36
@jas99 On `typescript-graphql-auth` if I replace `?` by `| null` in Parent Models, I get TS issues around Queries/Mutations using this model as return value (or in a payload which contains this model).

**Comment by kevinmarrec** [comment] 2018-10-10 13:37
And `typescript-graphql-auth` doesn't have the `strictNullChecks: true` in `tsconfig.json`

**Comment by jas99** [comment] 2018-10-10 13:37
@kevinmarrec strictNullChecks is on by default

**Comment by kevinmarrec** [comment] 2018-10-10 13:39
@jas99 Not for me in my editor

**Comment by jas99** [comment] 2018-10-10 13:43
@kevinmarrec when you do tsc --init; can you see  `"strict": true`, thr?

**Comment by kevinmarrec** [comment] 2018-10-10 13:47
@jas99 Well in my project I have a custom `tsconfig.json`, as `typescript-graphql-auth` does. Maybe `tsc --init` generate a filed with `strict: true` but it doesn't mean that `strict` has `true` as default value with an empty `tsconfig.json`

**Comment by kevinmarrec** [comment] 2018-10-10 13:48
But anyway with `strict: true` you should have issues in Queries/Mutations, using your solution with `| null`

**Comment by jas99** [comment] 2018-10-10 13:52
@jas99 Maybe thr are new changes; I will look into it. Meanwhile instead of `graphql-resolver-codegen` use `@jas99/graphql-resolver-codegen` and let me know if even this is breaking; caz I have tested this to be working.

**Comment by kevinmarrec** [comment] 2018-10-10 14:55
@divyenduz I tried locally to replace all `null` by `undefined` in `src/generated/resolvers.ts`, everything seems to be alright => 0 issues with TypeScript + Everything works fine executing GraphQL queries when requesting required/not-required fields. (GraphQL handle by itself undefined values to result as null in data responses)

Maybe should wereplace all `null` by `undefined` around resolver generation ?

**Comment by jas99** [comment] 2018-10-10 15:19
@kevinmarrec Check conversation at #51

**Comment by kevinmarrec** [comment] 2018-10-10 16:06
@jas99 Checked but I still don't know what is the problem ? It seems to be a choice by opinion and not a followed directive provided by GraphQL-Js (if i'm wrong please give me some references to read or code to know what's going on between using `undefined` or `null`)

**Comment by kevinmarrec** [comment] 2018-10-10 16:47
Prisma Client itself generates Model Nodes (UserNode for example) with `undefined` and not `null`, that's what cause typescript issues aroune mutations and queries as they must return something like Nodes Types but fail cause our Model Parent (UserParent refering to UserNode) results in type mismatching. (`undefined` !== `null`)

**Comment by schickling** [comment] 2018-10-22 12:28
I assume this has been fixed by the latest version. Please open a new issue if this problem still occurs.

**Closed by schickling** 2018-10-22 12:28 UTC
Labels: kind/bug

**Comment by cyrus-za** [comment] 2018-11-10 12:16
Check #278

**Comment by avatsaev** [comment] 2020-05-20 15:30
How do I update a date field to null or undefiend?
