### ISSUE TITLE
Resolvers interface not compatible with graphql-yoga IResolvers type

### ISSUE THREAD

**Issue by Callan93** [prisma/graphqlgen#209] opened 2018-10-27 13:06 UTC
## Description
The type of `graphql-yoga`'s resolvers (`IResolvers`) is not compatible with the `Resolvers` interface generated by `graphqlgen`.

I believe this is due to the typings of the `args` field in either case. 

`IFieldResolver` (`graphql-yoga`) gives `args` the type:  
```ts
TArgs = {
    [argument: string]: any;
}
```

The interface for `args` generated by `graphqlgen` is of the form 

```ts
  interface ArgsCreateItem {
    title: string
    description: string
    price: number
    image: string | null
    largeImage: string | null
  }
```

When attempting to create a graphql server with `new GraphQLServer(...)` and the `graphqlgen` typed resolvers, the following error is given:

```
[ts]
Type '{ Mutation: Type; Query: Type; }' is not assignable to type 'IResolvers<any, any> | IResolvers<any, any>[] | undefined'.
  Type '{ Mutation: Type; Query: Type; }' is not assignable to type 'undefined'.
types.d.ts(82, 5): The expected type comes from property 'resolvers' which is declared here on type 'Props<any, any, any>'
```

I managed to get around the issue by converting the expression to `unknown`:

![image](https://user-images.githubusercontent.com/5160266/47604414-3062d600-da2c-11e8-8f03-6b8723615992.png)

## Versions
- graphqlgen: 0.2.12
- OS name and version: Windows 10 Home

**Comment by schickling** [comment] 2018-11-03 20:11
Duplicate of #15

**Closed by schickling** 2018-11-03 20:11 UTC
