### ISSUE TITLE
Make IResolvers compatible with IResolvers from graphql-tools

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#15] opened 2018-08-16 08:33 UTC
![image](https://user-images.githubusercontent.com/1567498/44197743-d4ccc000-a13f-11e8-9b24-b3c3f1868cc6.png)

**Comment by juicycleff** [comment] 2018-08-21 09:54
Looking into this atm

**Comment by brikou** [comment] 2018-09-19 20:32
@juicycleff just upgrade to graphql-tools v4, see https://github.com/apollographql/graphql-tools/pull/932

**Comment by divyenduz** [comment] 2018-09-28 10:02
@juicycleff : Do you still want to take a stab at this one? 😉

**Comment by koenpunt** [comment] 2018-11-11 19:08
Duplicate of #15

**Comment by jplew** [comment] 2018-11-14 01:17
> @schickling upgrading to graphql-tools v4 should solve it, see [apollographql/graphql-tools#932](https://github.com/apollographql/graphql-tools/pull/932)

this does not solve the problem.

Hacky workaround, for anyone who can't wait until this gets resolved, is to cast resolvers to type `any`:

![image](https://user-images.githubusercontent.com/462836/48453297-9c04ad00-e767-11e8-97bd-d131e87b27c0.png)

Editing the resolver type in `graphqlgen.ts` will also work, but not recommended since your graphqlgen.ts will be overwritten the next time you run the tool:

![image](https://user-images.githubusercontent.com/462836/48453348-e0904880-e767-11e8-9587-4379935b924d.png)

**Comment by alexedev** [comment] 2018-11-16 12:55
Any update on this?

**Comment by maticzav** [comment] 2019-02-06 09:05
@schickling @jasonkuhrt @timsuchanek

**Comment by jasonkuhrt** [comment] 2019-02-06 13:33
The problem is a fundamental mismatch between assumptions made by graphqlgen vs Apollo server. Neither is wrong or put another way both are wrong from either one’s point of view. 

Apollo has used an index signature on their resolvers type which is not type safe. It allows any invalid prop to be added to resolvers. It makes sense for Apollo server because there is little type safety in its resolvers to begin with including no statically known information about the resolvers object props.

The any-cast is a cheap workaround.

We may be able to use interface declaration merging to have graphqlgen update the Apollo server options type. Ideal because it would require zero compromise from either tool (except for maintenance burden for us).

**Closed** 2019-02-09 03:37 UTC
Labels: area/generation, kind/feature
