### ISSUE TITLE
Generated `Resolvers` interface not compatible with `IResolvers` from graphql-tools

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#124] opened 2018-10-18 08:42 UTC
![image](https://user-images.githubusercontent.com/1567498/47142066-5f59a900-d2c2-11e8-9ef7-d7e045ed0aec.png)

Current workaround (add `as any`):

```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers: resolvers as any,
  context: { data },
})
``` 

My current understanding is that this is a limitation in `graphql-tools`. We should open an issue there.

**Comment by fedealconada** [comment] 2018-10-27 13:08
any workaround until it is fixed?

**Comment by schickling** [comment] 2018-10-29 19:02
See comment from above:

Current workaround (add `as any`):

```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers: resolvers as any,
  context: { data },
})
```

**Comment by alexedev** [comment] 2018-11-16 12:52
Same problem here

**Comment by rlux** [comment] 2019-02-06 13:42
I am using makeExecutableSchema.
For me the incompatibility with IResolvers  was caused by a missing index signature. All generated resolvers should have it. As a workaround, I declare my resolvers as "...Resolvers.Type & { [key: string]: any } ".

**Comment by jasonkuhrt** [comment] 2019-02-08 13:48
Duplicate of #15

**Closed by jasonkuhrt** 2019-02-08 13:48 UTC
Labels: area/generation, bug/2-confirmed, status/pr-welcome
